#spring:
#  h2:
#    console.enabled: true
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username:
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aftas
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update